language: java
before_script: echo "%{build_number}" > src/main/resources/build-number.txt
deploy:
  provider: releases
  api_key:
    secure: WJCFgLBHpvkSZhR+jrv62azbtwsipPjyvVKE19mqc1LFZ74b/2esLzPnE8RlDIf4ciaj4ohLzKpKysy1PkiDr+FaA4j3IjUBcqjoQbYmosjUqFEMepBSUuscxUWPVECq8cN5G6Fwi9RODzMYNjJKCatb24f0ehb1a3kvyqiKlhA=
  file: "target/cd-test-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

