language: java
before_install: echo "$TRAVIS_BUILD_NUMBER" > src/main/resources/build-number.txt
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DbuildNumber=$TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key:
    secure: WJCFgLBHpvkSZhR+jrv62azbtwsipPjyvVKE19mqc1LFZ74b/2esLzPnE8RlDIf4ciaj4ohLzKpKysy1PkiDr+FaA4j3IjUBcqjoQbYmosjUqFEMepBSUuscxUWPVECq8cN5G6Fwi9RODzMYNjJKCatb24f0ehb1a3kvyqiKlhA=
  file: "target/cd-test-$TRAVIS_BUILD_NUMBER.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

